{
  "hash": "9aa4c6b16372ecb4fbfb2bdc47d8fe39",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"PM 566 Final Project\"\nauthor: \"Giuliet Kibler\"\nformat: \n pdf: \n    embed-resources: true\neditor: visual\n---\n\n\n\n## Pre-Covid American Dietary Intention and B Vitamins\n\n# Introduction\n\nThe National Health and Nutrition Examination Survey is a survey, typically conducted over a two-year period, to estimate the dietary intake over the 24-hour period prior to the interview of Americans 1 year or older. This particular dataset is a combination of data collected in the 2017-2018 cycle and 2019-March 2020 since the NHANES program was suspended in March of 2020 due to the COVID-19 pandemic. The dietary interview component of this survey is called \"What We Eat in America\" (WWEIA) and data is collected using the USDA's Automated Multiple Pass Method (AMPM). All participants are eligible for two survey interviews, the first of which is recorded in person at the Mobile Examination Center, and the second is conducted over the phone 3 to 10 days later. This data set includes dietary information from the first interview and is a log of the total energy and nutrient intakes, including the macronutrients (carbohydrates, fats, and proteins) and vitamins, from foods and beverages within the previous 24-hours. Of particular interest in this dataset is whether participants intended diet (macronutrient dietary intention) aligns with their actual food consumption (dietary intake). Additionally, there is interest in assessing the relationship between dietary intake and the B vitamins intake. B vitamins are cofactors for many cellular pathways, including cellular metabolism and synthesis of DNA and RNA, but are not stored by the body, so it is critical to replenish them daily through foods and supplements (Hanna et al, 2022). Therefore, this analysis is to assess if Americans 1 year or older are eating their intended macronutrient diet and if their intake is associated with B vitamin levels pre-pandemic (2017-March 2020).\n\n# Methods\n\nThe P_DR1TOT dataset for 2017-March 2020 was downloaded from the CDC's NHANES records of dietary data. This is a dataset from the WWEIA day 1 interviews, conducted between 2017 and March of 2020, and includes total dietary intake of participants.\n\nData variables of interest include 6 variables of special diets, referred to here as intended diet, 5 energy (caloric) and macronutrient variables, and B vitamins 1, 2, and 6. These variables were extracted from the dataset and relabeled to be more informative. 12 intended diets were recorded in separate variables as numbers 1-12 for yes to that diet or missing for no. These variables were altered to 1 for yes and 0 for no. Since low calorie and high calorie diets are labeled separately, a new variable for diet was created where low calorie is 0, high calorie is 1, and neither is 2.\n\nCorrelation between intended macronutrient or caloric diet and true dietary intake was assessed using summary statistics and box plots.\n\nThe proportion of participants below the recommended B vitamins intake levels for men were reported. Recommendations for men are used, rather than splitting the data by sex, because sex is not reported in the dataset and female dietary recommendations are less studied in scientific literature. Correlation between dietary intake, as well as caloric diet type, and B vitamin levels was assessed using scatter plots and linear fitted models.\n\n\n\n::: {.cell}\n\n:::\n\n\n\n## Exploring Variables of Interest\n\n\n\n::: {.cell}\n\n:::\n\n\n\n### Figure 1. Distribution of Macronutrients for All Participants\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Final-Project_files/figure-pdf/unnamed-chunk-3-1.pdf)\n:::\n:::\n\n\n\nAll mean values for intake are increased by high outliers, so medians are assessed instead.\n\n### Table 1. Median Caloric, Macronutrient and B Vitamin Intake Levels\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\nTable: Total Median Caloric (cal), Macronutrient (g) and B Vitamin Intake Levels (mg)\n\n| Calories| Sugar| Carbohydrate|    Fat| Protein|   B1|   B2|    B6|\n|--------:|-----:|------------:|------:|-------:|----:|----:|-----:|\n|     1824| 90.81|        218.6| 71.815|   64.76| 1.31| 1.59| 1.489|\n\n\n:::\n:::\n\n\n\nThese median values are used to categorize whether dietary intake is high (above the median) or low (below the median).\n\n\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n:::\n\n\n\n# Preliminary Results\n\n## Investigate correlation between intended diet and dietary intake\n\n### Figure 2. Proportion of Participants with an Intended Macronutrient Diet Ingesting Above or Below the Total Median Intake\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Final-Project_files/figure-pdf/unnamed-chunk-8-1.pdf)\n:::\n:::\n\n\n\nApproximately 63% of participants on a low sugar diet are eating less than the median sugar levels, while nearly 75% of participants on a low carbohydrate diet are eating less than the median carbohydrate levels. Conversely, less than half of the participants are eating less than the median fat levels. Finally, more than 75% of participants are eating their intended high protein diet compared to the median protein levels.\n\nThese results show that a high protein diet is the most well adhered to diet when compared to the surveyed participants, while a low fat diet is the least well adhered to diet.\n\n## Compare the spread of macronutrient intake levels of participants with an intended diet with those not on an intended diet\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\nTable: Table 1. Summary of Sugar Intake\n\n|Low Diet |      Mean| Median|  Min|    Max| Count|\n|:--------|---------:|------:|----:|------:|-----:|\n|No       | 105.68458|  90.89| 0.00| 931.16| 14226|\n|Yes      |  81.42301|  62.24| 5.16| 414.14|    74|\n\n\n:::\n\n::: {.cell-output-display}\n\n\nTable: Table 2. Summary of Carbohydrate Intake\n\n|Low Carb Diet |     Mean|  Median|  Min|     Max| Count|\n|:-------------|--------:|-------:|----:|-------:|-----:|\n|No            | 239.5814| 219.080| 0.00| 1586.24| 14143|\n|Yes           | 178.5371| 165.395| 9.55|  673.39|   157|\n\n\n:::\n\n::: {.cell-output-display}\n\n\nTable: Table 3. Summary of Fat Intake\n\n|Low Fat Diet |     Mean| Median|  Min|    Max| Count|\n|:------------|--------:|------:|----:|------:|-----:|\n|No           | 81.03713| 71.805| 0.00| 567.96| 14154|\n|Yes          | 80.43219| 72.620| 5.72| 253.70|   146|\n\n\n:::\n\n::: {.cell-output-display}\n\n\nTable: Table 4. Summary of Protein Intake\n\n|High Protein Diet |      Mean| Median|   Min|    Max| Count|\n|:-----------------|---------:|------:|-----:|------:|-----:|\n|No                |  72.16154|  64.72|  0.00| 545.20| 14261|\n|Yes               | 108.33923| 100.61| 15.03| 309.18|    39|\n\n\n:::\n:::\n\n\n\n### Figure 3. Distribution of Macronutrient Dietary Intake by Diet Type\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Final-Project_files/figure-pdf/unnamed-chunk-10-1.pdf)\n:::\n:::\n\n\n\nThe low sugar group averaged lower total sugars than those not on the diet (62.24 vs 90.89 g). Additionally, the low carbohydrate group ate less carbohydrates than those not on this diet (165.395 vs 219.08 g). On the other hand, those on a low fat diet ate more fats than those not on the diet (72.62 vs 71.805 g), meaning the average participant on a low fat diet did not eat less fats than other participants. The average high protein diet had substantially more protein intake than those not on the diet (100.61 vs 64.72 g).\n\n### Table 5. Summary of Caloric Intake by Diet Type\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\nTable: Table 5. Summary of Caloric Intake\n\n|Diet              |     Mean| Median| Min|   Max| Count|\n|:-----------------|--------:|------:|---:|-----:|-----:|\n|High Calorie Diet | 2669.773|   2528| 553|  7632|    46|\n|Low Calorie Diet  | 1968.596|   1834| 100|  7375|   799|\n|Neither           | 1995.732|   1821|   0| 12501| 13455|\n\n\n:::\n:::\n\n\n\n### Figure 4. Distribution of Caloric Intake by Caloric Diet Type\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Final-Project_files/figure-pdf/unnamed-chunk-12-1.pdf)\n:::\n:::\n\n\n\nThe average high calorie diet included substantially higher caloric intake than either the low calorie diet or those not on a caloric diet (2528 vs 1834 and 1821 cals), but the low calorie diet was actually slightly higher than those not on a caloric diet (1834 vs 1821 cals), meaning the average participant on a low calorie diet ate more calories than those not intending to calorically restrict.\n\n## Investigate correlations between dietary intake and B vitamins\n\n### Table 6. Proportion of Participants Below B Vitamin Recommended Intake for Men (Hanna et al., 2022)\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|B Vitamin | Proportion of Participants Below Recommended Intake|\n|:---------|---------------------------------------------------:|\n|B1        |                                           0.4317301|\n|B2        |                                           0.3513557|\n|B6        |                                           0.2571821|\n\n\n:::\n:::\n\n\n\nThese results show that while most participants are taking their recommended B vitamin levels, between 25% and 43% of participants are not with B1 having the highest proportion of participants below the recommended levels and B6 having the lowest proportion below the recommended proportion.\n\n### Figure 5. B Vitamin Levels vs Dietary Intake\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Final-Project_files/figure-pdf/unnamed-chunk-14-1.pdf)\n:::\n:::\n\n\n\nRegressions were fit for each diet type to answer the question of whether macronutrient consumption impacts B vitamin levels. B1 and B2 vitamins are more strongly associated with all of the macronutrient intakes than B6. The highest correlations occurred between B1 and caloric intake and B1 and carbohydrate intake. The red dashed lines are used to represent the recommended B vitamin intake levels for men of 1.2 mg of B1, 1.3 miligrams (mg) of B2 and 1.0 mg of B6 from Table 6. Overall, this demonstrates that getting enough dietary nutrition is critical for B1 and B2 vitamin daily replenishment.\n\n### Figure 6. Caloric Diet's Effect on B vitamins\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Final-Project_files/figure-pdf/unnamed-chunk-15-1.pdf)\n:::\n\n::: {.cell-output-display}\n![](Final-Project_files/figure-pdf/unnamed-chunk-15-2.pdf)\n:::\n\n::: {.cell-output-display}\n![](Final-Project_files/figure-pdf/unnamed-chunk-15-3.pdf)\n:::\n:::\n\n\n\nB vitamins have a mild-to-moderate association with dietary intake. The high calorie diet in the graphs of vitamins B1 and B2 vs calories have the highest slopes, indicating that an intention to eat more calories is also associated with an increase in B vitamin intake. This finding makes sense given participants on a high calorie diet actually eat more calories and caloric intake was shown to be moderately associated with these B vitamin levels. Interestingly, caloric diet type's association with the B vitamins was not consistent between the vitamins, indicating that more just than dietary intention is necessary for sufficient B vitamin intake.\n\n# Conclusion\n\nOverall, the pre-pandemic (2017-March 2020) participants' intended diets is associated with their true intake. Specifically, participants on a low sugar and low carbohydrate diet ate less of these macronutrients than participants not on such a diet and participants with a high protein and high caloric diet ate more protein and overall calories, respectively, than participants without these dietary intentions. On the other hand, the average participant on a low fat and low calorie diet actually ate more fats or calories, respectively, than participants who did not report adhering to these diets. Thus, Americans 1 year or older are not eating their intended low fat and low calorie diets, when compared to the average diet, while all Americans eating all other assessed diets are follow their intended diets.\n\nOne draw back to this analysis is that all interquartile ranges of dietary intake by intended diet overlap with those not following the diet. Therefore, truly following an intended diet is variable among Americans during this time period. This lack of conclusivity makes since considering dietary needs are relative to a person's physiological demands.\n\n43% of participants are below the recommended B1 levels guidelines for men, 35% are below the guidelines for B2 levels, and 26% are below the guidelines for B6 levels. Due to the correlations demonstrated between B vitamins and dietary intake, many participants should eat more macronutrients and overall calories to meet the body's B vitamin demands. In conclusion, the average American 1 year or older is eating their intended macronutrient diet and their intake is moderately associated with B vitamin levels during this time period.\n",
    "supporting": [
      "Final-Project_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}